quali_gate_pid_node:
  ros__parameters:
    config_location: '/config/quali_gate_pid.yaml'

    PID_freq: 20.0
    PID_freq_min: 0.0
    PID_freq_max: 50.0
    PID_freq_step: 0.1

    x_Kp: 0.1
    x_Kp_min: 0.0
    x_Kp_max: 10.0
    x_Kp_step: 0.01

    x_Ki: 0.0
    x_Ki_min: 0.0
    x_Ki_max: 1.0
    x_Ki_step: 0.01

    x_Kd: 0.0
    x_Kd_min: 0.0
    x_Kd_max: 1.0
    x_Kd_step: 0.01

    x_kd_multiplier: 0.0
    x_kd_multiplier_min: 0.0
    x_kd_multiplier_max: 5.0
    x_kd_multiplier_step: 1.0

    x_ki_multiplier: 0.0
    x_ki_multiplier_min: 0.0
    x_ki_multiplier_max: 5.0
    x_ki_multiplier_step: 1.0

    sides_ratio_Kp: 0.0
    sides_ratio_Kp_min: 0.0
    sides_ratio_Kp_max: 500.0
    sides_ratio_Kp_step: 1.0

    sides_ratio_Ki: 0.0
    sides_ratio_Ki_min: 0.0
    sides_ratio_Ki_max: 1.0
    sides_ratio_Ki_step: 0.01

    sides_ratio_Kd: 0.0
    sides_ratio_Kd_min: 0.0
    sides_ratio_Kd_max: 1.0
    sides_ratio_Kd_step: 0.01

    sides_ratio_kd_multiplier: 0.0
    sides_ratio_kd_multiplier_min: 0.0
    sides_ratio_kd_multiplier_max: 5.0
    sides_ratio_kd_multiplier_step: 1.0

