thruster_allocator_node:
  ros__parameters:
    config_location: '/config/simple_direction_test.yaml'

    x: 100.0
    x_min: 0.0
    x_max: 200.0
    x_step: 1.0

    y: 100.0
    y_min: 0.0
    y_max: 200.0
    y_step: 1.0

    z: 100.0
    z_min: 0.0
    z_max: 200.0
    z_step: 1.0
