vert_pid_node:
  ros__parameters:
    config_location: '/config/vert_pid_test.yaml'

    PID_freq: 20.0
    PID_freq_min: 0.0
    PID_freq_max: 50.0
    PID_freq_step: 0.1

    desired_yaw: 150.0
    desired_yaw_min: -180.0
    desired_yaw_max: 180.0
    desired_yaw_step: 1.0

    desired_depth: -1.0
    desired_depth_min: -2.0
    desired_depth_max: 0.0
    desired_depth_step: 0.1

    depth_Kp: 65.0
    depth_Kp_min: 0.0
    depth_Kp_max: 500.0
    depth_Kp_step: 1.0

    depth_Ki: 0.0
    depth_Ki_min: 0.0
    depth_Ki_max: 1.0
    depth_Ki_step: 0.01

    depth_Kd: 140.0
    depth_Kd_min: 0.0
    depth_Kd_max: 1.0
    depth_Kd_step: 0.01

    roll_Kp: 0.0
    roll_Kp_min: 0.0
    roll_Kp_max: 1.0
    roll_Kp_step: 0.01

    roll_Ki: 0.0
    roll_Ki_min: 0.0
    roll_Ki_max: 1.0
    roll_Ki_step: 0.01

    roll_Kd: 0.0
    roll_Kd_min: 0.0
    roll_Kd_max: 1.0
    roll_Kd_step: 0.01

    pitch_Kp: 0.0
    pitch_Kp_min: 0.0
    pitch_Kp_max: 1.0
    pitch_Kp_step: 0.01

    pitch_Ki: 0.0
    pitch_Ki_min: 0.0
    pitch_Ki_max: 1.0
    pitch_Ki_step: 0.01

    pitch_Kd: 0.0
    pitch_Kd_min: 0.0
    pitch_Kd_max: 1.0
    pitch_Kd_step: 0.01

    yaw_Kp: 0.0
    yaw_Kp_min: 0.0
    yaw_Kp_max: 1.0
    yaw_Kp_step: 0.01

    yaw_Ki: 0.0
    yaw_Ki_min: 0.0
    yaw_Ki_max: 1.0
    yaw_Ki_step: 0.01

    yaw_Kd: 0.0
    yaw_Kd_min: 0.0
    yaw_Kd_max: 1.0
    yaw_Kd_step: 0.01

    depth_kd_multiplier: 0.0
    depth_kd_multiplier_min: 0.0
    depth_kd_multiplier_max: 5.0
    depth_kd_multiplier_step: 1.0

    depth_ki_multiplier: 0.0
    depth_ki_multiplier_min: 0.0
    depth_ki_multiplier_max: 5.0
    depth_ki_multiplier_step: 1.0

    ki_multiplier: 0.0
    ki_multiplier_min: 0.0
    ki_multiplier_max: 5.0
    ki_multiplier_step: 1.0

    kd_multiplier: 1.0
    kd_multiplier_min: 0.0
    kd_multiplier_max: 5.0
    kd_multiplier_step: 1.0
